<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <BuiltInImplicitValueTuple>true</BuiltInImplicitValueTuple>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

  </PropertyGroup>


	<ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="FFMpegCore" Version="5.4.0" />
    
    <PackageReference Include="SkiaSharp" Version="4.150.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
  </ItemGroup>
</Project>